---

- hosts: centos.my
  become: yes
  tasks:
  - name: Install postgresql-12 rpm
    shell: yum -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  - name: Install postgresql-12 server
    shell: yum install -y postgresql12-server
  - name: Install postgresql-12 initdb
    shell: /usr/pgsql-12/bin/postgresql-12-setup initdb
    notify:
      postgresql-12 systemd

  handlers:
  - name: postgresql-12 systemd
    systemd:
     name: postgresql-12.service
     enabled: yes
     state: started
